#START A NEW LINE AFTER LATEST SCRIPT
random-wallpaper = ~/.config/hypr/scripts/random-wallpaper.sh
waybar-selection = ~/.config/waybar/waybar-selector.sh
waybar-color = ~/.config/waybar/scripts/color-swapper.sh
toggle-battery = ~/.config/ofa/scripts/toggle-wifi-power.sh
toggle-tailscale = ~/.config/ofa/scripts/toggle-tailscale.sh
